name: wickedhair
favicon: null
layout_spectrum: 0.7349618803709745
typography_spectrum: 0.2956550675444305
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8491735639981925
  lightness: 0.5600122979376465
  saturation: 0.9896047287620604
  rhythmicContrast: 0.5249694492667913
purpose: []
